version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
services:
  - postgresql
jobs:
  environment:
    NODE_ENV: test
  database:
    override:
      - echo psql -c "create database employeems_test;" -U postgres
  steps:
    - checkout
    - run: npm install
    # - run: npm test
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install-npm
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: "migrations"
        command: npm run migrate
    - run: # run tests
        name: test
        command: npm run test
    - run: # run code coverage report
        name: code-coverage
        command: npm run coverage
    - coveralls/upload
    - store_artifacts: # special step to save test results as as artifact
      # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      path: test-results
        prefix: tests
    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: coverage
        prefix: coverage
    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: test-results
    - run: # test what branch we're on.
        name: "What branch am I on?"
        command: echo ${CIRCLE_BRANCH}